name: tests-gmchanges

on: 
  pull_request:
    paths:
      - 'gmchanges/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd gmchanges && npm install && npm run test:ci
