export async function getSkills(character: any) {

    const skills = [
            {name: 'Fliegen' , value: character?.skills?.Flying || 0 },
            {name: 'Gaukelei' , value: character?.skills?.Gaukelei || 0 },
            {name: 'Klettern' , value: character?.skills?.Climbing || 0 },
            {name: 'Körperbeherrschung' , value: character?.skills?.BodyControl || 0 },
            {name: 'Kraftakt' , value: character?.skills?.FeatOfStrength || 0 },
            {name: 'Reiten' , value: character?.skills?.Riding || 0 },
            {name: 'Schwimmen' , value: character?.skills?.Swimming || 0 },
            {name: 'Selbstbeherrschung' , value: character?.skills?.SelfControl || 0 },
            {name: 'Singen' , value: character?.skills?.Singing || 0 },
            {name: 'Sinnenschärfe' , value: character?.skills?.Perception || 0 },
            {name: 'Tanzen' , value: character?.skills?.Dancing || 0 },
            {name: 'Taschendiebstahl' , value: character?.skills?.Pickpocket || 0 },
            {name: 'Verbergen' , value: character?.skills?.Stealth || 0 },
            {name: 'Bekeheren' , value: character?.skills?.Carousing || 0 },
            {name: 'Überzeugen' , value: character?.skills?.Persuasion || 0 },
            {name: 'Betören' , value: character?.skills?.Seduction || 0 },
            {name: 'Einschüchtern' , value: character?.skills?.Intimidation || 0 },
            {name: 'Etikette' , value: character?.skills?.Etiquette || 0 },
            {name: 'Gassenwissen' , value: character?.skills?.Streetwise || 0 },
            {name: 'Menschenkenntnis' , value: character?.skills?.Empathy || 0 },
            {name: 'Überreden' , value: character?.skills?.FastTalk || 0 },
            {name: 'Sich verkleiden' , value: character?.skills?.Disguise || 0 },
            {name: 'Willenskraft' , value: character?.skills?.Willpower || 0 },
            {name: 'Fährtensuchen' , value: character?.skills?.Tracking || 0 },
            {name: 'Fesseln' , value: character?.skills?.Ropes || 0 },
            {name: 'Angeln/Fischen' , value: character?.skills?.Fishing || 0 },
            {name: 'Orientierung' , value: character?.skills?.Orienting || 0 },
            {name: 'Pflanzenkunde' , value: character?.skills?.PlantLore || 0 },
            {name: 'Tierkunde' , value: character?.skills?.AnimalLore || 0 },
            {name: 'Wildnisleben' , value: character?.skills?.Survival || 0 },
            {name: 'Brettspiel/Glücksspiel' , value: character?.skills?.Gambling || 0 },
            {name: 'Geographie' , value: character?.skills?.Geography || 0 },
            {name: 'Geschichtswissen' , value: character?.skills?.History || 0 },
            {name: 'Religion' , value: character?.skills?.Religions || 0 },
            {name: 'Kriegskunst' , value: character?.skills?.Warfare || 0 },
            {name: 'Magiekunde' , value: character?.skills?.MagicalLore || 0 },
            {name: 'Mechanik' , value: character?.skills?.Mechanics || 0 },
            {name: 'Rechnen' , value: character?.skills?.Math || 0 },
            {name: 'Rechtskunds' , value: character?.skills?.Law || 0 },
            {name: 'Sagen und Legenden' , value: character?.skills?.MythsAndLegends || 0 },
            {name: 'Spherenkunde' , value: character?.skills?.SphereLore || 0 },
            {name: 'Sternenkunde' , value: character?.skills?.Astronomy || 0 },
            {name: 'Alchemie' , value: character?.skills?.Alchemy || 0 },
            {name: 'Segeln' , value: character?.skills?.Sailing || 0 },
            {name: 'Fahrzeuge lenken' , value: character?.skills?.Driving || 0 },
            {name: 'Handel' , value: character?.skills?.Commerce || 0 },
            {name: 'Heilkunde Gift' , value: character?.skills?.TreatPoison || 0 },
            {name: 'Heilkunde Krankheiten' , value: character?.skills?.TreatDisease || 0 },
            {name: 'Heilkunde Seele' , value: character?.skills?.TreatSoul || 0 },
            {name: 'Heilkunde Wunden' , value: character?.skills?.TreatWounds || 0 },
            {name: 'Holzbearbeitung' , value: character?.skills?.Woodworking || 0 },
            {name: 'Lebensmittelbearbeitung' , value: character?.skills?.PrepareFood || 0 },
            {name: 'Lederbearbeitung' , value: character?.skills?.Leatherworking || 0 },
            {name: 'Malen/Zeichnen' , value: character?.skills?.ArtisticAbility || 0 },
            {name: 'Metallbearbeitung' , value: character?.skills?.Metalworking || 0 },
            {name: 'Musizieren' , value: character?.skills?.Music || 0 },
            {name: 'Schlösser knacken' , value: character?.skills?.PickLocks || 0 },
            {name: 'Bergbau' , value: character?.skills?.Earthencraft || 0 },
            {name: 'Stofbearbeitung' , value: character?.skills?.Clothworking || 0 },
        ];

    return skills;

}