apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmchanges-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmchanges
  template:
    metadata:
      labels:
        app: gmchanges
    spec:
      containers:
        - name: gmchanges
          image: gcr.io/saon-dev/gmchanges
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: saon
            - name: MONGO_URI
              value: 'mongodb://gmchanges-mongo-srv:27017/gmchanges'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gmchanges-srv
spec:
  selector:
    app: gmchanges
  ports:
    - name: gmchanges
      protocol: TCP
      port: 3000
      targetPort: 3000