name: tests-wiki

on: 
  pull_request:
    paths:
      - 'wiki/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd wiki && npm install && npm run test:ci