name: tests-characters

on: 
  pull_request:
    paths:
      - 'characters/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd characters && npm install && npm run test:ci
